enable_disqus: false
enable_analytics: false
highlighter: rouge
permalink: pretty

_url: http://localhost:4000
#_url: https://flaviomicheletti.github.io/regex
#_url: http://www.devfuria.com.br/regex

secao: regex

defaults:
  -
    scope:
      path: ""
    values:
      layout: "artigo"
